// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuifotpzonzkhqchsomb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1aWZvdHB6b256a2hxY2hzb21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTU1NDksImV4cCI6MjA3NDkzMTU0OX0.OaEOBfy3eZ9ZHO_KHwg8gNMwW13PI_rLsTol4rooiic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});